### ISSUE TITLE
library 是不是不能用？

### ISSUE THREAD

**Issue by czn6** [saymagic/Daffodil#1]
尝试着在 library里使用 build 报了这个错：
Error:(21, 0) Cannot cast object 'com.android.build.gradle.LibraryExtension_Decorated@311c1f1b' with class 'com.android.build.gradle.LibraryExtension_Decorated' to class 'com.android.build.gradle.AppExtension'

**Comment by saymagic** [comment]
是的，library目前还没有做支持。在计划里。

**Comment by czn6** [comment]
好的 支持一下~加油
