### ISSUE TITLE
Error:Could not find daffodil-lib.jar (tech.saymagic:daffodil-lib:1.1.0)

### ISSUE THREAD

**Issue by waylife** [saymagic/Daffodil#2]
Hey magic:
I follow the instruction but it doesn't work.
![image](https://user-images.githubusercontent.com/3348620/28904688-525a3afa-783f-11e7-8646-8fba1a0e8c3a.png)

ERROR
![image](https://user-images.githubusercontent.com/3348620/28904737-a39a5ecc-783f-11e7-9b4d-1823c17fd2f2.png)

Is that means I should compile the plugin myself.

**Comment by saymagic** [comment]
Sorry, this is my mistake, in the `compile` field did not write "@aar".

Please change

```
compile 'tech.saymagic:daffodil-lib:1.1.0'
```

to

```
compile 'tech.saymagic:daffodil-lib:1.1.0@aar'
```

**Comment by waylife** [comment]
Thx a lot, it works.
