### ISSUE TITLE
What's the relation or difference with JakeWharton/hugo?

### ISSUE THREAD

**Issue by drakeet** [saymagic/Daffodil#3]
The library looks great, but its usage and API much like Hugo, so I would like to ask: What's the difference with JakeWharton's Hugo?

Hugo: https://github.com/JakeWharton/hugo

Thanks!

**Comment by saymagic** [comment]
Hogo is an awesome library, this library was also inspired by Hogo.

The difference is Hogo based on AspectJ, This library based on ASM. It's my practice project when learning ASM.

**Comment by drakeet** [comment]
OK. Thank you for your sharing and answer!
